### ISSUE TITLE
The bugs on dropdown

### ISSUE THREAD

**Issue by Mady-Camara** [OpenCodeDev/OpenCodeDev.Blazor.Foundation#9]
1. The "Position" attribute is required otherwise the dropdown is not displayed. Normally it must be a Bottom if it does not exist
2. The dropdown does not remain on the button on which it is applied. In case of scroll it remains on the screen
3. Dropdowns do not exclude themselves, they all stay on the screen

**Comment by maxgsamson** [comment]
i have pushed changes to the branch create-dropdown.
the issue is related to the way our layout was made which is not a recommendable way to do that! to fix the issue we must change the layout.

**Comment by Mady-Camara** [comment]
Ok, So it’s just the layout that needs to be changed

**Comment by maxgsamson** [comment]
indeed, frame grid style does not play well with dropdown.

**Comment by maxgsamson** [comment]
@A-San96 @Mady-Camara i confirm, changing the layout fixed this issue.
